weniv/weniv_world

assets/css/main.css, assets/py/character.py, assets/py/coordinate.py, assets/py/error.py, assets/py/wall.py, index.html
- 맵의 테두리를 누르면 벽이 추가
- 벽이 존재하는 경우에 벽을 추가할 수 없습니다. (wall만 적용, door 적용X)
- 벽 좌표는 아래 이미지를 참고바랍니다.
- 현재 wall만 추가되며, door은 초기 데이터에 넣어두었습니다. -> 이동 가능한 벽은 노랑, 이동 불가한 벽은 파랑
- wall-container의 자식 요소로 벽이 추가되며, 좌표값에 따라 position (top, bottom, left, right) 값 지정
- 월드 초기화 버튼 클릭 시, 새로운 wall-data를 이용하여 초기화  
- `new_wall_data = {'wall': [], 'door': [(3,8),(4,7)]}`
- character.py에 movable 함수를 선언
- 기존 위치 (x, y)와 이동할 위 (nx, ny)를 인자로 전달하여 (1)이동위치가 맵 안에 있는지 (2)이동 경로에 벽이 있는지 판별
- 이동이 불가능한 경우 오류 메시지 출력
<br/>
- 가장 좌측 축에 벽이 추가되지 않습니다. -> 외곽선에는 벽을 추가하지 못하도록 수정하거나 추가되도록 설정
- 벽 종류 선택하여 추가
- 초기화 외에 특정 벽 삭제
=> Feat/wall: 벽 기능 구현

assets/py/coordinate.py, index.html
- coordinate의 wall_type을 선언하여, 추가될 벽의 타입을 지정합니다
- wall_type은 input[radio] 태그로 선택할 수 있습니다.
=> Feat: Wall type을 설정할 수 있는 라디오 추가

assets/css/main.css, assets/py/wall.py, index.html
- 벽 타입 delete 선택 후, 지도 상의 벽을 클릭하면 삭제됩니다.
- 방향(direction)과 벽 타입(type) 사용을 위하여 class -> dataset 으로 수정했습니다.
- 사용자가 추가한 벽에 대하여 mouseenter, mouseleave 이벤트가 올바르게 동작하지 않아 수정할 예정입니다.
=> Feat: 벽 삭제 로직 구현

assets/py/character.py
- x, y 방향이 달라져 move_line이 올바르게 동작하지 않았습니다.
- x, y 방향과 draw_move_line 호출 시, 매개변수도 수정했습니다.
=> :bug: Fix: moveline 방향 오류 수정

.gitignore, assets/css/main.css, assets/py/character.py, index.html
_move 함수 내 회전 값 변경
rotate값을 가져와 누적하여 뺀 값을 style에 추가
=> :bug: 회전 에러 수정

assets/js/resizer.js
- 누락된 파일 및 추가 수정이 필요해 다시 PR 올립니다.
=> 📝 PR: notebook, world, output, story 섹션 크기 조정 기능 #12 (수정)

assets/pyscript/pyscript.js, assets/pyscript/pyscript_latest.js
메서드 자동완성 기능 제외
메서드 자동완성 기능을 수행하는 pyscript-latest 파일 수정
=> # 📝 PR: 메서드 자동완성 기능 Disable

LICENSE.txt, README.md, assets/pyscript/pyscript.js, assets/pyscript/pyscript_latest.js
📝 PR: 라이센스 파일 추가 및 readme.md 추가, 자동 메서드 툴팁 Active 
- pyscript 라이센스 및 위니브월드 라이센스 전문 추가
- 자동 메서드 툴팁 Active
=> 📝 PR: 라이센스 파일 추가 및 readme.md 추가, 자동 메서드 툴팁 Active 

index.html
- 초기화 버튼 클릭 후 캐릭터 정보가 나오지 않는 현상 수정
- 객체 삭제시 연결된 이벤트도 삭제됨으로서 동작하지 않았음.
```from pyodide.ffi.wrappers import add_event_listener```
코드를 통해 새롭게 생성한 캐릭터에 이벤트를 다시 연결시켜야됩니다.
- None
=> 📝 PR: 초기화시 캐릭터 정보 노출 오류 수정

assets/py/built_in_functions.py
set_item 메서드 오류 수정를 수정하였습니다.
set_item 메서드에 pick 메서드를 추가하여 
메서드 호출 시 캐릭터의 현재 위치에 아이템이 생성된다면 개수를 1을 증가시킵니다.
- None
=> 📝 PR: 위니브월드 set_item 메서드 오류 수정

.gitignore, assets/css/style.css, package-lock.json, package.json
- 컴파일러 통일성을 위하여 node-sass를 설치하였습니다.
1. node-sass 설치: `npm i`
2. 컴파일 명령어: `npm run scss`
- styls.scss를 style.css로 변환합니다.
=> :lipstick: Add: node-sass 설치

assets/pyscript/pyscript_latest.js
함수 자동완성 기능을 비활성화 하였습니다.
pyscript.latest.js 파일의 함수 자동완성 함수들을 주석처리하였습니다.
=> 📝 PR: 위니브월드 함수 자동완성 기능 Disabled

assets/css/_world.scss, assets/css/style.css, assets/py/built_in_functions.py, assets/py/coordinate.py, assets/py/item.py, package.json
- set_item 메서드 type 및 x, y 범위 오류 예외 처리
- 아이템을 map-item(맵의 한 칸)으로 포함시킨 후, 스타일 속성 변경
- `set_item(x, y, name)`의 x, y에 대한 예외 처리를 진행했습니다. type이 잘못 들어왔을 경우와, 범위가 map_data를 벗어나는 경우 오류 메시지를 출력합니다.
- 아이템이 map-item(맵의 한 칸)으로 포함된 후, position 속성을 변경하였습니다.
- map-item에 `position:relative` 속성을 준 후, 아이템 이미지와 개수 요소를 배치했습니다.
=> 📝 PR: 아이템 예외 처리 및 position 스타일 수정

assets/py/built_in_functions.py
=> :bug: Fix: set_item pick 예외처리

assets/py/character.py, index.html
- 캐릭터 속도 조절 문제 수정
- 캐릭터 초기화 후 속도 조절 함수 연결
- 속도 조절 슬라이더 바의 값을 기반으로
`running_speed = ((100 - int(slider.value))/10) + 0.1`
값을 적용하여 캐릭터의 속도를 조절합니다.
- 캐릭터가 초기화 된 이후에도 현재 슬라이더 바의 값을 기반으로 속도를 조절합니다.
=> 📝 PR: 캐릭터 속도 조절 적용 코드 수정

assets/py/item.py
동일 좌표 set_item 메서드 실행에 대한 예외 처리
- 좌표에 해당하는 map-item(`self.target`)의 자식요소가 있는지 확인합니다.
- 자식요소가 있는 경우, item 이름과 개수를 객체로 반환합니다.
```py
if(self.target.hasChildNodes()): #self.target == map_item
item = self.target.querySelector('.item')
count = self.target.querySelector('.count').innerHTML
return {'name': list(item.classList)[1], 'count': count}
```
- 같은 아이템을 추가하는 경우 Count를 증가시킵니다.
- 기존 자식 요소를 삭제하고, 새로운 자식 요소를 추가하는 방식입니다.
```py
target_item = self.item_exist()
if(target_item):
if(target_item['name'] == self.name):
self.set_count(self.count + int(target_item['count']))
self.target.removeChild(self.target.querySelector('.item-container'))
....
```
close #80
=> :sparkles: Feat: set_item 메서드 예외 처리

assets/py/built_in_functions.py, assets/py/character.py, assets/py/coordinate.py, assets/py/error.py, assets/py/item.py, assets/py/map.py, assets/py/modules.py, assets/py/wall.py, obfuscate_file.py, package-lock.json, package.json, webpack.config.js
Webpack 번들링, workflow 생성
Webpack 번들링을 통환 난독화 및 CI/CD 테스트를 위한 Workflow 파일을 생성하였습니다.
=> 📝 PR: Webpack 적용 및 CI/CD 테스트

.vscode/settings.json, assets/py/character.py
- 병합 충돌 수정, import wall_data 추가
=> :ambulance: Fix: wall_data import

assets/py/character.py
- 경로명에 오타가 있어 수정합니다 `wall_dat` -> `wall-data`
=> :pencil2: Edit: 오타 수정

index.html
- 스토리보드에서 pointerEvent가 none이 되는 요소를 변경
- map-container에 pointerEvent 속성을 변경하는 경우, 자식요소인 캐릭터의 정보가 출력X
- wall-container(벽 추가 방지)와 map-items(아이템 추가 방지)에 pointEvent를 등록하였습니다.
=> :ambulance: Fix: 스토리 모드에서 캐릭터 정보 출력 수정

assets/py/item.py
- 월드에 추가될 아이템의 경로를 상대경로로 수정합니다.
=> :ambulance: Fix: 아이템 이미지 경로 수정

assets/js/event.js, index.html
- 모달 닫기 버튼을 클릭하면 클립보드 이벤트가 동작하는 문제를 해결하였습니다.
- 변수 리스트를 수정하였습니다.
=> 🐛 Bug: 모달 닫기 버튼 이벤트 동작 확인 #127

index.html
- 캐릭터를 클릭했을 때 표시되는 캐릭터 정보에서 캐릭터 초기화 버튼을 클릭하면 캐릭터 정보가 초기화 되도록 합니다.
- 캐릭터 정보 모달은 처음 html 파일이 로드될 때 존재하지 않는 요소이기 때문에 이벤트 리스너가 추가되지 않은 문제를 확인하였습니다.
- 캐릭터 정보 모달이 생길 때 해당 이벤트가 추가되도록 수정하였습니다.
=> :sparkles: Add: 캐릭터 정보 모달에 이벤트 리스너 추가 #131

assets/py/built_in_functions.py, index.html
- show_item 메서드를 실행했을 때 return이 아닌 print를 통해 출력되도록 수정하였습니다.
=> ✨ Feat: show_item() 수정 #134

index.html
아이템을 추가하면 item_data에 추가되는 로직을 생성했습니다.
월드 데이터를 업, 다운로드를 수행하고 아이템을 추가하면 `item_data`에 추가되지 않은 경우가 있었습니다.
=> 📝 PR: 아이템 추가시 `item_data`에 추가하는 로직 생성

assets/py/built_in_functions.py, assets/py/character.py, index.html
=> :memo: PR: 메서드명 변경 open->open_door

assets/py/built_in_functions.py
`show_item` 함수의 반환값을 수정하여 정상적으로 아이템의 갯수를 가져오게 하였습니다.
=> 📝 PR: show_item 버그 수정

assets/py/character.py
`pick` 메서드 내 item의 갯수를 줄이는 동작이 수행되지 않아 해결하였습니다.
=> 📝 PR: pick 메서드 버그 수정

assets/data/story/story1.md, assets/data/story/story5.md, assets/data/story/story9.md
=> 📝 PR: 스토리 테스트 반영

assets/js/resizer.js, assets/py/character.py
- 월드를 벗어나는 좌표의 벽 탐색 오류 예외처리
- 삭제된 파일(resizer.js) 복구
=> 📝 PR: 사라진 파일 복구 및 예외처리

assets/py/built_in_functions.py, index.html
- 출력 메서드 딜레이 처리
- 애니메이션 딜레이를 위한 변수명 통일 `command_count`
- 전역 변수 running_speed로 값을 가져오지 못하여, dom 요소의 값으로  처리 진행
```py
a = 0.00020004
b = -0.0408163393
c = 2.5411162993
slider = js.document.getElementById("speed-range")
slider_output = js.document.getElementById("speed-text")
slider_output.innerHTML = slider.value
running_speed = a * int(slider.value)**2 + b * int(slider.value) + c
return running_speed
```
close #146
=> 📝 PR: 출력(print, say) 메서드 속도 조절

assets/py/character.py
- put 메서드 동작 수정
- 오류 메시지 추가  
close #150 
1. 기존의 비동기 코드가 삭제되지 않아서, _put 메서드가 2번 동작하여 오류 발생
```py
setTimeout(
create_once_callable(lambda: (self._put(item_name))), self.running_time
)
setTimeout(create_once_callable(lambda: self.init_time()), self.running_time
```
2. 아이템이 바닥에 없는 경우 아이템이 추가되는 로직 추가
```py
item_data[(x,y)]= {"item":item_name,"count":1}
```
- NoItem: 아이템 pick , put 시 아이템 없음
- AnotherItemInBottom: 캐릭터의 위치에 다른 아이템이 있.
```py
def move_item():
pick()
move()
put('fish-1')
mission_start()
set_item(0,0,'fish-1')
repeat(2,move_item)
mission_end()
```
=> 📝 PR: put 오류 수정

assets/css/_main.scss, assets/css/style.css, index.html
- 케밥 메뉴 스타일 수정
- 교안 파일 추가(/assets/documents)
- 링크 클릭하면 다운로드 되도록 파일 연결
=> 📝 PR: 교안 연결 및 스타일 추가 작업 #158

assets/py/built_in_functions.py, index.html
- 맵 크기 변경 후 벽 추가 오류 수정
- 맵 크기 변경 후 아이템 추가 오류 수정
- mdraw_map으로 새로운 맵 DOM 요소 생성
- wall_container가 맵 DOM에 추가되지 않아 오류 발생
```py
def change_map(evt=None):
wall.resizeWall(map_data['width'], map_data['height'])
wall_container = wall.drawWall()
wall_data['world'] = wall.wall_data
draw_map.appendChild(wall_container) # 자식 요소 추가
```
- 요소의 좌표값을 올바르게 가져가지 못해 오류 발생
- 중복으로 아이템이 추가되는 오류
- 추가하고자 하는 위치에 동일한 아이템 있을 때 개수 추가 / 없을 때는 새로 추가
```py
count = 1
if item_data.get((x,y))==item_select['name']:
item_data[(x,y)]['count'] += count
else:
item_data[(x,y)] = {
'item': item_select['name'],
'count': count
}
```
close #161
=> 📝 PR: 맵 크기 변경 후, 이벤트 동작 오류 수정 #161

assets/py/built_in_functions.py, assets/py/character.py, assets/py/coordinate.py, assets/py/mob.py, index.html
- 몹 추가 메서드 변경
- 몹 메서드 처리를 위한 클래스 생성
```py
lion = add_mob(2, 4, 'lion')
```
- 사용 가능 메서드: move, turn_left, attack, draw_move_line
- mob_data로 접근
```py
[{'mob': 'lion', 'mop_obj': <mob.Mob object at 0x100d0d0>, 'x': 2, 'y': 4, 'directions': 0}]
```
=> 📝 PR: 몹 추가

assets/py/mob.py, index.html
- 몹 구분을 위한 name 값 추가 및 메서드 수정 #167
- 메서드를 실행할 때, DOM 요소를 선택하기 위하여 querySelector 사용 -> 첫번째 추가된 요소가 선택되어 의도한 동작X
- 구분을 위한 값이 필요 -> 기존의 lion, mob1, mob2, mob3는 몹의 종류 구분자로 사용 / 유니크한 값이 name을 추가하여 관리
- 데이터 형태도 변경
```py
def add_mob(x=4, y=4, mob_type=None, name=None):
```
```
#mob.py 
{
"name": self.name,
"mob": self.mob,
"x": self.x,
"y": self.y,
"directions": self.directions,
}
```
- class로 name을 지정하고 querySelector를 하게되는 경우, name이 mob_type과 같은 경우 문제가 발생
- id를 `mob-${name}` 값으로 지정하여 요소 선택 시 구분될 수 있도록 수정
close #167
=> 📝 PR: 몹 구분을 위한 값 추가 및 인자 수정

assets/py/mob.py, index.html
- 몹 move 후 위치 값 수정
- 몹 move() 후, 맵 크기 변경 시 위치가 변경되는 이슈 발생
- lion, mob1/2/3의 종류에 따라 위치값의 수식이 다름. **추ㅎ
```py
if self.mob =='lion':
if directions == 0:
c.style.left = f"{(y + 1) * 100 + 2 + (50 - 32) + 13}px"
self.draw_move_line(x, y, x, y + 1, directions)
elif directions == 1:
c.style.top = f"{(x - 1) * 100 + 2 + (50 - 32) + 8}px"
self.draw_move_line(x, y, x-1, y, directions)
elif directions == 2:
c.style.left = f"{(y - 1) * 100 + 2 + (50 - 32) + 13}px"
self.draw_move_line(x, y, x, y - 1, directions)
elif directions == 3:
c.style.top = f"{(x + 1) * 100 + 2 + (50 - 32) + 8}px"
self.draw_move_line(x, y, x + 1, y, directions)
elif self.mob[:3]=='mob':
if directions == 0:
c.style.left = f"{(y + 1) * 100 + 2 + (50 - 32) + 21}px"
self.draw_move_line(x, y, x, y + 1, directions)
elif directions == …
```
=> 📝 PR: 몹 move 위치값 수정

assets/py/character.py, assets/py/coordinate.py, assets/py/mob.py, index.html
- 기본 캐릭터 설정 (character_data[0], 기본값: licat)
- 기본 캐릭터의 위치보다 맵이 작아질 수 없습니다.
- 기본 캐릭터의 체력이 0이 되었을 때, 마지막 위치에서 부활할 수 있습니다.
- character_data[0]을 기본 캐릭터로 설정합니다.
- 기본값은 licat 입니다.
- 맵 변경 시, 캐릭터가 맵을 벗어나지 못하도록 예외처리 진행
```py
main_ch = character_data[0]
initX = map_data['height']
initY = map_data['width']
if main_ch['x'] > int(map_slider_x.value) - 1 or main_ch['y'] > int(map_slider_y.value) - 1:
js.alert(f"기본 캐릭터의 위치보다 작게 맵을 설정할 수 없습니다.")
map_slider_x.value = initX
map_slider_y.value = initY
map_slider_output_x.innerHTML = initX
map_slider_output_y.innerHTML = initY
return
```
- 공격으로 기본 캐릭터의 체력이 0이 되었을 때 부활할 수 있습니다. (js.confirm)
- 부활하지 않는 경우, `character_data[0] = {} `으로 처리하여, move(), attack()과 같은 메서드 실행 시 오류가 발생합니다.
=> 📝 PR: 기본 캐릭터 설정

assets/js/event.js, assets/py/built_in_functions.py, assets/py/character.py, assets/py/coordinate.py, assets/py/error.py, assets/pyscript/pyscript_latest.js, index.html
- eat(item_name)으로 아이템을 섭취할 수 있습니다.
- 임시로 fish, apple 이 섭취 가능합니다.
- item을 섭취하여 캐릭터의 체력과 힘을 증가시킬 수 있습니다.
=> 📝 PR: 아이템 섭취 메서드 추가

assets/py/built_in_functions.py, assets/py/character.py, assets/pyscript/pyscript_latest.js
- 결과코드가 출력되지 않아 try-except 구문을 제외했습니다.
- 관련이슈: #184 
- ipynb 노트북의 경우 마지막 줄의 명령어가 값이면 py-repl 하단에 해당 값을 출력합니다.
- 오류가 발생한 경우 py-repl 하단에 해당 정보를 출력합니다.
- 값의 경우 print로 출력되나, 오류 확인이 어려워 일단 try-except 구문을 제외했습니다.
=> :memo: PR: 전처리 코드 수정

assets/py/modules.py
- jump 메서드로 앞으로 2칸 이동할 수 있습니다.
- 캐릭터 앞에 장애물이 있는 경우, jump 메서드를 이용하여 뛰어 넘을 수 있습니다.
- 최종 위치(앞으로 2칸)에 장애물이 없는 경우에만 메서드가 수행됩니다.
- 클래스 내부에서 사용되는 메소드를 이용하여 처리를 진행합니다.
close #192
=> :sparkles: Feat: jump 메서드 구현

index.html
- 아이템 추가 후, 이전 선택 아이템이 표시되는 오류 수정
=> :ambulance: Fix: 아이템 추가 후, 아이템 선택 표시 삭제

assets/py/built_in_functions.py, assets/py/character.py
- [front|left|right|back]_is_clear() 장애물 처리 수정
- 캐릭터와 몹이 존재하는 경우 False를 반환합니다.
- front_is_clear()메서드를 사용하므로, 벽 이외에도 다른 캐릭터, 장애물이 있는 경우 이동하지 않습니다.
=> 📝 PR: 장애물 로직 수정

assets/py/built_in_functions.py, assets/py/character.py, assets/py/coordinate.py, assets/py/error.py, assets/py/mob.py, assets/py/modules.py, index.html
- 캐릭터 추가 함수에서 캐릭터 유효성 검사를 진행합니다.
- 공격으로 캐릭터가 사라졌을 때 예외처리를 진행합니다.
- 현재 유효한 캐릭터: [라이캣]
- 유효하지 않은 캐릭터를 추가하는 경우 오류를 발생합니다.
- character_info의 key값으로 유효 캐릭터를 판별합니다.
```py
character_info = {
'licat':{
'hp':100,
'mp':100,
'skills':['claw-yellow','claw-white','beam','explosion']
}
}
```
- 캐릭터가 공격을 받아 체력이 0이 되는경우, 기본 캐릭터 삭제 가능
- 기본 캐릭터(licat) 추가 시, character_data의 첫번째 요소로 추가
- 화면에 기본 캐릭터가 없고, 다른 캐릭터가 존재하는 경우 -> move() 메서드 수행 시, 첫번째 요소가 이동
=> 📝 PR: 캐릭터 추가 유효성 검사

index.html
- ipynb 노트북 업로드 오류 수정
- 코드 블록 최하단 요소만 auto-generate
- cell.source가 코드로 이뤄진 문자열 -> join 메서드가 수행되지 않고 오류 발생 #203
- 마지막 코드 블록만 auto-generate 속성을 가짐.
- 파일의 코드 블록이 항상 마지막 자식요소로 들어감.   
-> 기존 코드 블록의 auto-generate 속성 제거
-> 마지막 cell 요소에 auto-generate 속성 추가
close #203
=> 🚑 Hotfix: ipynb 노트북 업로드 오류 수정

assets/py/character.py
=> :memo: Edit: 벽이 있으면 공격이 불가

webpack.config.js
- 캐시 무효화
- 사용자 입장에서 강력 새로고침을 수행하지 않도록 캐시 무효화
- hashcontent사용
- 배포 페이지에서 확인 예정
- 오류 발생 시 Revert 하겠습니다
=> :package: Add: 웹팩 캐시 무효화를 위한 hash값 추가

assets/css/_world.scss, assets/py/built_in_functions.py, assets/py/character.py, assets/py/error.py, index.html
- show_modal_alert를 이용하여 3초 뒤에 사라지는 모달창을 동적으로 생성합니다.
- 경고창이 독립적으로 동작합니다. → 경고창이 연달아서 뜨는 경우 타이머 오류 발생X
=> :memo: PR: 모달창 동적 생성

assets/py/built_in_functions.py
- DOM 요소 변수명 오타 수정
- 정답 알람 창 출력
=> 📝 PR: 변수명 오타 수정

assets/py/character.py, assets/py/coordinate.py, assets/py/error.py, assets/py/mob.py, index.html
=> :memo: Add: 함수 및 변수 리스트 추가

assets/py/character.py, index.html
- 월드 불러온 후 몹 추가 이벤트 등록
- 맵 불러온 후 아이템 위치 변경 오류 수정
=> 📝 PR: 맵 업로드 관련 QA 오류 수정
